### ISSUE TITLE
ILookup is not a protocol warning

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [dribnet/mrhyde#2]
When I start the cljsbuild REPL, I get this warning, twice:

```
WARNING: Symbol ILookup is not a protocol at line 248 file:/home/leonidas/.m2/repository/net/drib/mrhyde/0.5.3/mrhyde-0.5.3.jar!/mrhyde/typepatcher.cljs
```

I suppose something changed inside ClojureScript, that causes this warning.

**Comment by dribnet** [comment]
All warnings should now be gone when compiling or starting repl. Please let me know if this is not the case.
