### ISSUE TITLE
.defineProperty causes problems in IE

### ISSUE THREAD

**Issue by beandipper** [dribnet/mrhyde#4]
Mrhyde is incompatible with IE 8 because of the unsupported defineProperty function.

The culprit is [at line 36 in mrhyde's typepatcher source](https://github.com/dribnet/mrhyde/blob/master/src/cljs/mrhyde/typepatcher.cljs#L36). Not sure if there is another way to write that function without defineProperty, but there are solutions out there as long as the defineProperty is being called on DOM objects,  although i'm not sure that is what your library is doing.

**Comment by dribnet** [comment]
Closing this for now as wontfix - not sure what would be involved supporting IE and tests confirmed to be passing in firefox and chrome.
