### ISSUE TITLE
Warnings from mrhyde when trying to use strokes with latest cljs

### ISSUE THREAD

**Issue by seancorfield** [dribnet/mrhyde#5]
WARNING: Referred var clojure.string/re-matches does not exist at line 2 file:/Users/sean/.m2/repository/net/drib/mrhyde/0.5.3/mrhyde-0.5.3.jar!/mrhyde/mrhyde.cljs

This seems harmless as re-matches is not actually used.

WARNING: No such namespace: cljs.core.ObjMap at line 536 file:/Users/sean/.m2/repository/net/drib/mrhyde/0.5.3/mrhyde-0.5.3.jar!/mrhyde/typepatcher.cljs

This is repeated several times.

WARNING: Referred var mrhyde.mrhyde/recurse-from-hyde-cache does not exist at line 1 file:/Users/sean/.m2/repository/net/drib/mrhyde/0.5.3/mrhyde-0.5.3.jar!/mrhyde/funpatcher.cljs

???

**Comment by matevarga** [comment]
mrhyde is not compatible with the latest cljs version, unfortunately. See other issue.

**Comment by dribnet** [comment]
Thanks to #7, mrhyde now compiles without any warnings in whitespace and simple optimization modes, and all tests passing in chrome and firefox. Please reopen if you find otherwise.
