### ISSUE TITLE
update mrhyde to latest cljs

### ISSUE THREAD

**Issue by dribnet** [dribnet/mrhyde#6]
The mrhyde library has not been updated in over a year. It would be great if someone could verify that it is working on the latest cljs version. There is a fairly through test suite accessed via [mrhyde--test.html](https://github.com/dribnet/strokes/blob/master/public/mrhyde-test.html) that will test features with three different compilation settings.

**Comment by matevarga** [comment]
Please take a look at https://github.com/dribnet/mrhyde/pull/7

**Comment by dribnet** [comment]
Resolved, thanks!
